In [1]:

import pandas as pd
import numpy as np
import os
import warnings

In [3]:
RAW_DATA_PATH = "../data/raw"

print("Raw data folder:", RAW_DATA_PATH)
print("Files available:")

for file in os.listdir(RAW_DATA_PATH):
    print(" -", file)

Raw data folder: ../data/raw
Files available:
 - City.xlsx
 - Continent.xlsx
 - Country.xlsx
 - Item.xlsx
 - Mode.xlsx
 - Region.xlsx
 - Transaction.xlsx
 - Type.xlsx
 - Updated_Item.xlsx
 - User.xlsx

In [7]:
cities_path = os.path.join(RAW_DATA_PATH, "Cities.xlsx")

cities_path = os.path.normpath(cities_path)

if not os.path.isfile(cities_path):
    alternative_path = os.path.join(RAW_DATA_PATH, "City.xlsx")

    if os.path.isfile(alternative_path):
        cities_path = os.path.normpath(alternative_path)
    else:
        raise FileNotFoundError(
            f"Neither Cities.xlsx nor City.xlsx was found at "
            f"{os.path.abspath(cities_path)}. "
            f"Available files: {os.listdir(RAW_DATA_PATH)}"
        )

cities = pd.read_excel(cities_path)

print("Cities dataset loaded successfully.")

Cities dataset loaded successfully.

In [8]:
cities.head(10)

   CityId         CityName  CountryId
0       0                -          0
1       1           Douala          1
2       2     South Region          1
3       3        N'Djamena          2
4       4           Kigali          3
5       5  Kigali Province          3
6       6      Addis Ababa          4
7       7            Karen          5
8       8            Kenya          5
9       9          Malindi          5

In [9]:
cities.tail(10)

      CityId   CityName  CountryId
9133    9133       Yarm        163
9134    9134       Yate        163
9135    9135     Yaxham        163
9136    9136     Yeadon        163
9137    9137  Yelverton        163
9138    9138     Yeovil        163
9139    9139       York        163
9140    9140  Yorkshire        163
9141    9141    Zaandam        163
9142    9142      Sanaa        164

In [10]:
rows, columns = cities.shape

print(f"Number of rows    : {rows:,}")
print(f"Number of columns : {columns}")

Number of rows    : 9,143
Number of columns : 3

In [11]:
print("Columns in Cities dataset:\n")

for i, column in enumerate(cities.columns, start=1):
    print(f"{i}. {column}")

Columns in Cities dataset:

1. CityId
2. CityName
3. CountryId

In [12]:
cities.dtypes

CityId        int64
CityName     object
CountryId     int64
dtype: object

In [13]:
cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9143 entries, 0 to 9142
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CityId     9143 non-null   int64
 1   CityName   9142 non-null   object
 2   CountryId  9143 non-null   int64
dtypes: int64(2), object(1)
memory usage: 214.4+ KB

In [14]:
cities.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
CityId,9143.0,NaN,NaN,NaN,4571.0,2639.501089,0.0,2285.5,4571.0,6856.5,9142.0
CityName,9142,8767,-,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CountryId,9143.0,NaN,NaN,NaN,107.776878,42.466496,0.0,69.0,109.0,151.0,164.0

In [15]:
missing_count = cities.isnull().sum()
missing_percentage = (cities.isnull().sum() / len(cities)) * 100

missing_summary = pd.DataFrame({
    "Missing_Count": missing_count,
    "Missing_Percentage": missing_percentage.round(2)
})

missing_summary

           Missing_Count  Missing_Percentage
CityId                 0                0.00
CityName               1                0.01
CountryId              0                0.00

In [16]:
duplicate_count = cities.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [17]:
duplicate_city_ids = cities["CityId"].duplicated().sum()

print("Duplicate CityId values:", duplicate_city_ids)

Duplicate CityId values: 0

In [18]:
for column in cities.columns:
    print(f"{column}: {cities[column].nunique():,} unique values")

CityId: 9,143 unique values
CityName: 8,767 unique values
CountryId: 164 unique values

In [19]:
print("Minimum CityId:", cities["CityId"].min())
print("Maximum CityId:", cities["CityId"].max())
print("Unique CityIds:", cities["CityId"].nunique())

Minimum CityId: 0
Maximum CityId: 9142
Unique CityIds: 9143

In [20]:
print("Minimum CountryId:", cities["CountryId"].min())
print("Maximum CountryId:", cities["CountryId"].max())
print("Unique CountryIds:", cities["CountryId"].nunique())

Minimum CountryId: 0
Maximum CountryId: 164
Unique CountryIds: 164

In [21]:
cities_per_country = (
    cities.groupby("CountryId")
    .size()
    .reset_index(name="CityCount")
    .sort_values("CityCount", ascending=False)
)

cities_per_country.head(10)

     CountryId  CityCount
109        109       1782
51          51       1509
162        163       1232
101        101        295
48          48        283
161        162        278
93          93        263
158        159        237
125        125        231
115        115        200

In [22]:
city_frequency = (
    cities["CityName"]
    .value_counts()
    .reset_index()
)

city_frequency.columns = ["CityName", "Count"]

city_frequency.head(20)

       CityName  Count
0             -      8
1      Richmond      5
2      Victoria      4
3      Hamilton      4
4    Georgetown      4
5       Windsor      4
6     Cambridge      4
7        Albany      4
8      Kingston      4
9      Somerset      3
10     Waterloo      3
11   Alexandria      3
12         Leon      3
13      Denmark      3
14       Bexley      3
15      Ipswich      3
16  Southampton      3
17      Cardiff      3
18      Bedford      3
19      Chelsea      3

In [23]:
blank_city_names = cities["CityName"].astype(str).str.strip().eq("").sum()

print("Blank CityName values:", blank_city_names)

Blank CityName values: 0

In [24]:
print("Null CityId:", cities["CityId"].isnull().sum())
print("Null CountryId:", cities["CountryId"].isnull().sum())

Null CityId: 0
Null CountryId: 0

In [25]:
print("CityId data type:", cities["CityId"].dtype)
print("CountryId data type:", cities["CountryId"].dtype)
print("CityName data type:", cities["CityName"].dtype)

CityId data type: int64
CountryId data type: int64
CityName data type: object

In [26]:
cities.sample(min(15, len(cities)), random_state=42)

      CityId          CityName  CountryId
1162    1162            Hayden         51
3045    3045            Bitung        101
711      711        Bar Harbor         51
1570    1570    North Bethesda         51
2471    2471  Taoyuan District         74
2510    2510            Tehran         77
3784    3784           Bargara        109
7755    7755             Hoorn        162
9059    9059        West Wales        163
4019    4019     central coast        109
7571    7571             Ardee        160
668      668           Anaheim         51
2874    2874           Silchar         93
5360    5360   Wentworth Falls        109
743      743        Birmingham         51

In [27]:
inspection_summary = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Duplicate Rows",
        "Duplicate CityId",
        "Missing CityId",
        "Missing CityName",
        "Missing CountryId",
        "Unique Cities",
        "Unique Countries"
    ],
    "Value": [
        len(cities),
        len(cities.columns),
        cities.duplicated().sum(),
        cities["CityId"].duplicated().sum(),
        cities["CityId"].isnull().sum(),
        cities["CityName"].isnull().sum(),
        cities["CountryId"].isnull().sum(),
        cities["CityName"].nunique(),
        cities["CountryId"].nunique()
    ]
})

inspection_summary

              Metric  Value
0               Rows   9143
1            Columns      3
2     Duplicate Rows      0
3   Duplicate CityId      0
4     Missing CityId      0
5   Missing CityName      1
6  Missing CountryId      0
7      Unique Cities   8767
8   Unique Countries    164

In [30]:
print("TOURISM EXPERIENCE ANALYTICS")
print("TASK 1 - DATA INSPECTION REPORT")


print(f"\nDataset Name       : Cities")
print(f"Rows               : {cities.shape[0]:,}")
print(f"Columns            : {cities.shape[1]}")
print(f"Duplicate Rows     : {cities.duplicated().sum():,}")
print(f"Duplicate City IDs : {cities['CityId'].duplicated().sum():,}")
print(f"Missing Values     : {cities.isnull().sum().sum():,}")
print(f"Unique Cities      : {cities['CityName'].nunique():,}")
print(f"Unique Countries   : {cities['CountryId'].nunique():,}")

print("\nColumns:")
for column in cities.columns:
    print(f"  - {column}")

TOURISM EXPERIENCE ANALYTICS
TASK 1 - DATA INSPECTION REPORT

Dataset Name       : Cities
Rows               : 9,143
Columns            : 3
Duplicate Rows     : 0
Duplicate City IDs : 0
Missing Values     : 1
Unique Cities      : 8,767
Unique Countries   : 164

Columns:
  - CityId
  - CityName
  - CountryId

DATA CLEANING & QUALITY ANALYSIS

In [32]:
missing_city_name = cities[cities["CityName"].isnull()]

print("Rows with missing CityName:")
display(missing_city_name)

Rows with missing CityName:

      CityId CityName  CountryId
6879    6879      NaN        151

In [33]:
missing_city_name_index = cities[cities["CityName"].isnull()].index

print("Missing CityName row index:", missing_city_name_index.tolist())

for index in missing_city_name_index:
    print("\nRecord:")
    print(cities.loc[index])

Missing CityName row index: [6879]

Record:
CityId       6879
CityName      NaN
CountryId     151
Name: 6879, dtype: object

In [34]:
for index in missing_city_name_index:
    start = max(0, index - 3)
    end = min(len(cities), index + 4)

    print(f"\nRecords around index {index}:")
    display(cities.iloc[start:end])

Records around index 6879:

      CityId CityName  CountryId
6876    6876   Murano        151
6877    6877   Naples        151
6878    6878  Nettuno        151
6879    6879      NaN        151
6880    6880   Novara        151
6881    6881  Novello        151
6882    6882    Padua        151

In [35]:
for index in missing_city_name_index:
    city_id = cities.loc[index, "CityId"]
    country_id = cities.loc[index, "CountryId"]

    print(f"CityId   : {city_id}")
    print(f"CountryId: {country_id}")

CityId   : 6879
CountryId: 151

In [36]:
print(cities.dtypes)

CityId        int64
CityName     object
CountryId     int64
dtype: object

In [37]:
city_names = cities["CityName"].dropna().astype(str)

leading_spaces = city_names.str.startswith(" ").sum()
trailing_spaces = city_names.str.endswith(" ").sum()

print("Names with leading spaces :", leading_spaces)
print("Names with trailing spaces:", trailing_spaces)

Names with leading spaces : 0
Names with trailing spaces: 0

In [38]:
empty_city_names = (
    cities["CityName"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

print("Empty CityName values:", empty_city_names)

Empty CityName values: 1

In [39]:
duplicate_city_names = (
    cities[cities["CityName"].notna()]
    .groupby("CityName")
    .size()
    .reset_index(name="Count")
    .sort_values("Count", ascending=False)
)

duplicate_city_names.head(20)

         CityName  Count
0               -      8
6300     Richmond      5
98         Albany      4
3699     Kingston      4
2572   Georgetown      4
2878     Hamilton      4
1223    Cambridge      4
7988     Victoria      4
8362      Windsor      4
622       Bedford      3
1442      Chelsea      3
354       Atlanta      3
1923      Denmark      3
3293      Ipswich      3
1028     Brighton      3
4100         Leon      3
2571  George Town      3
1293      Cardiff      3
4483    Mansfield      3
4635    Melbourne      3

In [40]:
repeated_names = duplicate_city_names[
    duplicate_city_names["Count"] > 1
]

print("Number of repeated city names:",
      len(repeated_names))

display(repeated_names.head(20))

Number of repeated city names: 323

         CityName  Count
0               -      8
6300     Richmond      5
98         Albany      4
3699     Kingston      4
2572   Georgetown      4
2878     Hamilton      4
1223    Cambridge      4
7988     Victoria      4
8362      Windsor      4
622       Bedford      3
1442      Chelsea      3
354       Atlanta      3
1923      Denmark      3
3293      Ipswich      3
1028     Brighton      3
4100         Leon      3
2571  George Town      3
1293      Cardiff      3
4483    Mansfield      3
4635    Melbourne      3

In [41]:
city_country_check = (
    cities[cities["CityName"].notna()]
    .groupby("CityName")["CountryId"]
    .nunique()
    .reset_index(name="UniqueCountryCount")
    .sort_values("UniqueCountryCount", ascending=False)
)

display(
    city_country_check[
        city_country_check["UniqueCountryCount"] > 1
    ].head(20)
)

         CityName  UniqueCountryCount
0               -                   8
6300     Richmond                   5
98         Albany                   4
3699     Kingston                   4
2572   Georgetown                   4
2878     Hamilton                   4
1223    Cambridge                   4
7988     Victoria                   4
8362      Windsor                   4
622       Bedford                   3
1442      Chelsea                   3
354       Atlanta                   3
1923      Denmark                   3
3293      Ipswich                   3
1028     Brighton                   3
4100         Leon                   3
2571  George Town                   3
1293      Cardiff                   3
4483    Mansfield                   3
4635    Melbourne                   3

In [42]:
city_index = cities[cities["CityId"] == 6879].index[0]

display(
    cities.iloc[
        max(0, city_index - 5): city_index + 6
    ]
)

      CityId  CityName  CountryId
6874    6874  Monvalle        151
6875    6875     Monza        151
6876    6876    Murano        151
6877    6877    Naples        151
6878    6878   Nettuno        151
6879    6879       NaN        151
6880    6880    Novara        151
6881    6881   Novello        151
6882    6882     Padua        151
6883    6883   Palermo        151
6884    6884     Parma        151

In [43]:
country_151_cities = cities[
    cities["CountryId"] == 151
].sort_values("CityId")

print(f"Number of cities with CountryId 151: {len(country_151_cities)}")

display(country_151_cities)

Number of cities with CountryId 151: 156

      CityId                       CityName  CountryId
6793    6793                 Agrate Brianza        151
6794    6794                         Ancona        151
6795    6795  Appiano sulla Strada del Vino        151
6796    6796                          Arese        151
6797    6797                         Arezzo        151
...      ...                            ...        ...
6944    6944                    Ventimiglia        151
6945    6945                       Verbania        151
6946    6946                         Verona        151
6947    6947                        Vicenza        151
6948    6948       Villafranca in Lunigiana        151

[156 rows x 3 columns]

In [44]:
city_6879 = cities[cities["CityId"] == 6879]

print("CityId 6879 exists:", not city_6879.empty)
print("\nRecord:")
display(city_6879)

CityId 6879 exists: True

Record:

      CityId CityName  CountryId
6879    6879      NaN        151

In [45]:
expected_ids = set(range(cities["CityId"].min(),
                         cities["CityId"].max() + 1))

actual_ids = set(cities["CityId"])

missing_ids = expected_ids - actual_ids
extra_ids = actual_ids - expected_ids

print("Missing CityIds:", missing_ids)
print("Unexpected CityIds:", extra_ids)

Missing CityIds: set()
Unexpected CityIds: set()

In [46]:
cities_cleaned = cities.copy()

print("Cleaning copy created.")
print("Original shape :", cities.shape)
print("Working shape  :", cities_cleaned.shape)

Cleaning copy created.
Original shape : (9143, 3)
Working shape  : (9143, 3)

In [47]:
cities_cleaned["CityName"] = (
    cities_cleaned["CityName"]
    .astype("string")
    .str.strip()
)

print("CityName whitespace cleaned.")

CityName whitespace cleaned.

In [48]:
empty_city_names = (
    cities_cleaned["CityName"]
    .fillna("")
    .str.strip()
    .eq("")
)

print("Empty CityName values:", empty_city_names.sum())
print("Missing CityName values:", cities_cleaned["CityName"].isna().sum())

Empty CityName values: 1
Missing CityName values: 1

In [49]:
print("CityId missing:", cities_cleaned["CityId"].isna().sum())
print("CityId duplicates:", cities_cleaned["CityId"].duplicated().sum())

print("CountryId missing:", cities_cleaned["CountryId"].isna().sum())

CityId missing: 0
CityId duplicates: 0
CountryId missing: 0

In [50]:
negative_city_ids = (cities_cleaned["CityId"] < 0).sum()
negative_country_ids = (cities_cleaned["CountryId"] < 0).sum()

print("Negative CityId values:", negative_city_ids)
print("Negative CountryId values:", negative_country_ids)

Negative CityId values: 0
Negative CountryId values: 0

In [51]:
print("CityId dtype   :", cities_cleaned["CityId"].dtype)
print("CountryId dtype:", cities_cleaned["CountryId"].dtype)
print("CityName dtype :", cities_cleaned["CityName"].dtype)

CityId dtype   : int64
CountryId dtype: int64
CityName dtype : string

In [52]:
print("Duplicate rows:", cities_cleaned.duplicated().sum())
print("Duplicate CityId:", cities_cleaned["CityId"].duplicated().sum())

Duplicate rows: 0
Duplicate CityId: 0

In [54]:
city_country_duplicates = (
    cities_cleaned[
        cities_cleaned["CityName"].notna()
    ]
    .duplicated(
        subset=["CityName", "CountryId"],
        keep=False
    )
)

print(
    "Duplicate CityName + CountryId records:",
    city_country_duplicates.sum()
)

display(
    cities_cleaned.loc[
        city_country_duplicates[city_country_duplicates].index
    ]
    .sort_values(["CityName", "CountryId"])
    .head(30)
)

Duplicate CityName + CountryId records: 0

Empty DataFrame
Columns: [CityId, CityName, CountryId]
Index: []

In [55]:
quality_report = pd.DataFrame({
    "Column": cities_cleaned.columns,
    "Data_Type": [
        str(cities_cleaned[col].dtype)
        for col in cities_cleaned.columns
    ],
    "Missing_Count": [
        cities_cleaned[col].isna().sum()
        for col in cities_cleaned.columns
    ],
    "Missing_Percentage": [
        round(cities_cleaned[col].isna().mean() * 100, 2)
        for col in cities_cleaned.columns
    ],
    "Unique_Values": [
        cities_cleaned[col].nunique(dropna=True)
        for col in cities_cleaned.columns
    ]
})

display(quality_report)

      Column Data_Type  Missing_Count  Missing_Percentage  Unique_Values
0     CityId     int64              0                0.00           9143
1   CityName    string              1                0.01           8767
2  CountryId     int64              0                0.00            164

In [56]:
print("=" * 60)
print("CITIES DATASET - CLEANING STATUS")
print("=" * 60)

print(f"Rows                  : {len(cities_cleaned):,}")
print(f"Columns               : {len(cities_cleaned.columns)}")
print(f"Duplicate rows        : {cities_cleaned.duplicated().sum()}")
print(f"Duplicate CityId      : {cities_cleaned['CityId'].duplicated().sum()}")
print(f"Missing CityId        : {cities_cleaned['CityId'].isna().sum()}")
print(f"Missing CityName      : {cities_cleaned['CityName'].isna().sum()}")
print(f"Missing CountryId     : {cities_cleaned['CountryId'].isna().sum()}")

print("\nCleaning actions completed:")
print("✓ CityName whitespace removed")
print("✓ CityId validated")
print("✓ CountryId validated")
print("✓ Duplicate rows checked")
print("✓ Duplicate CityId checked")
print("✓ Data types verified")

print("\n⚠ CityName for CityId 6879 is still missing.")
print("It will NOT be guessed or removed until related datasets are checked.")

============================================================
CITIES DATASET - CLEANING STATUS
============================================================
Rows                  : 9,143
Columns               : 3
Duplicate rows        : 0
Duplicate CityId      : 0
Missing CityId        : 0
Missing CityName      : 1
Missing CountryId     : 0

Cleaning actions completed:
✓ CityName whitespace removed
✓ CityId validated
✓ CountryId validated
✓ Duplicate rows checked
✓ Duplicate CityId checked
✓ Data types verified

⚠ CityName for CityId 6879 is still missing.
It will NOT be guessed or removed until related datasets are checked.

In [57]:
processed_path = "../data/processed/Cities_cleaned.csv"

cities_cleaned.to_csv(
    processed_path,
    index=False
)

print("Cleaned Cities dataset saved successfully:")
print(processed_path)

Cleaned Cities dataset saved successfully:
../data/processed/Cities_cleaned.csv