In [1]:
import pandas as pd
import numpy as np

In [3]:
DATA_PATH = "../data/raw/"

transaction = pd.read_excel(DATA_PATH + "Transaction.xlsx")
user = pd.read_excel(DATA_PATH + "User.xlsx")
city = pd.read_excel(DATA_PATH + "City.xlsx")
country = pd.read_excel(DATA_PATH + "Country.xlsx")
region = pd.read_excel(DATA_PATH + "Region.xlsx")
continent = pd.read_excel(DATA_PATH + "Continent.xlsx")
item = pd.read_excel(DATA_PATH + "Item.xlsx")
type_df = pd.read_excel(DATA_PATH + "Type.xlsx")
mode = pd.read_excel(DATA_PATH + "Mode.xlsx")

print("All datasets loaded successfully.")

All datasets loaded successfully.

In [4]:
def clean_columns(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
    )
    return df


transaction = clean_columns(transaction)
user = clean_columns(user)
city = clean_columns(city)
country = clean_columns(country)
region = clean_columns(region)
continent = clean_columns(continent)
item = clean_columns(item)
type_df = clean_columns(type_df)
mode = clean_columns(mode)

In [5]:
print("Transaction:", transaction.columns.tolist())
print("User:", user.columns.tolist())
print("City:", city.columns.tolist())
print("Country:", country.columns.tolist())
print("Region:", region.columns.tolist())
print("Continent:", continent.columns.tolist())
print("Item:", item.columns.tolist())
print("Type:", type_df.columns.tolist())
print("Mode:", mode.columns.tolist())

Transaction: ['transactionid', 'userid', 'visityear', 'visitmonth', 'visitmode', 'attractionid', 'rating']
User: ['userid', 'continentid', 'regionid', 'countryid', 'cityid']
City: ['cityid', 'cityname', 'countryid']
Country: ['countryid', 'country', 'regionid']
Region: ['region', 'regionid', 'continentid']
Continent: ['continentid', 'continent']
Item: ['attractionid', 'attractioncityid', 'attractiontypeid', 'attraction', 'attractionaddress']
Type: ['attractiontypeid', 'attractiontype']
Mode: ['visitmodeid', 'visitmode']

In [6]:
print("Transaction VisitMode values:")
print(sorted(transaction["visitmode"].dropna().unique()))

print("\nMode table:")
print(mode)

Transaction VisitMode values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Mode table:
   visitmodeid visitmode
0            0         -
1            1  Business
2            2   Couples
3            3    Family
4            4   Friends
5            5      Solo

In [7]:
print("\nMode IDs:")
print(mode["visitmodeid"].unique())

print("\nMode names:")
print(mode["visitmode"].unique())

Mode IDs:
[0 1 2 3 4 5]

Mode names:
['-' 'Business' 'Couples' 'Family' 'Friends' 'Solo']

In [8]:
master = transaction.merge(
    user,
    on="userid",
    how="left",
    validate="many_to_one"
)

print("Transaction rows:", len(transaction))
print("Master rows after User merge:", len(master))

Transaction rows: 52930
Master rows after User merge: 52930

In [9]:
master = master.rename(columns={
    "continentid": "user_continentid",
    "regionid": "user_regionid",
    "countryid": "user_countryid",
    "cityid": "user_cityid"
})

In [10]:
master.head()

,transactionid,userid,visityear,visitmonth,visitmode,attractionid,rating,user_continentid,user_regionid,user_countryid,user_cityid
0,3,70456,2022,10,2,640,5,5,21,163,4341.0
1,8,7567,2022,10,4,640,5,2,8,48,464.0
2,9,79069,2022,10,3,640,5,2,9,54,774.0
3,10,31019,2022,10,3,640,3,5,17,135,583.0
4,15,43611,2022,10,2,640,3,5,21,163,1396.0

In [11]:
city_user = city.rename(columns={
    "cityid": "user_cityid",
    "cityname": "user_cityname",
    "countryid": "user_city_countryid"
})

master = master.merge(
    city_user,
    on="user_cityid",
    how="left",
    validate="many_to_one"
)

print("Rows after city merge:", len(master))

Rows after city merge: 52930

In [12]:
country_user = country.rename(columns={
    "countryid": "user_countryid",
    "country": "user_country",
    "regionid": "user_country_regionid"
})

master = master.merge(
    country_user,
    on="user_countryid",
    how="left",
    validate="many_to_one"
)

print("Rows after country merge:", len(master))

Rows after country merge: 52930

In [13]:
region_user = region.rename(columns={
    "regionid": "user_regionid",
    "region": "user_region",
    "continentid": "user_region_continentid"
})

master = master.merge(
    region_user,
    on="user_regionid",
    how="left",
    validate="many_to_one"
)

print("Rows after region merge:", len(master))

Rows after region merge: 52930

In [14]:
continent_user = continent.rename(columns={
    "continentid": "user_continentid",
    "continent": "user_continent"
})

master = master.merge(
    continent_user,
    on="user_continentid",
    how="left",
    validate="many_to_one"
)

print("Rows after continent merge:", len(master))

Rows after continent merge: 52930

In [15]:
master = master.merge(
    item,
    on="attractionid",
    how="left",
    validate="many_to_one"
)

print("Rows after attraction merge:", len(master))

Rows after attraction merge: 52930

In [16]:
master = master.merge(
    type_df,
    on="attractiontypeid",
    how="left",
    validate="many_to_one"
)

print("Rows after attraction type merge:", len(master))

Rows after attraction type merge: 52930

In [17]:
city_attraction = city.rename(columns={
    "cityid": "attractioncityid",
    "cityname": "attraction_cityname",
    "countryid": "attraction_countryid"
})

master = master.merge(
    city_attraction,
    on="attractioncityid",
    how="left",
    validate="many_to_one"
)

print("Rows after attraction city merge:", len(master))

Rows after attraction city merge: 52930

In [18]:
country_attraction = country.rename(columns={
    "countryid": "attraction_countryid",
    "country": "attraction_country",
    "regionid": "attraction_regionid"
})

master = master.merge(
    country_attraction,
    on="attraction_countryid",
    how="left",
    validate="many_to_one"
)

print("Rows after attraction country merge:", len(master))

Rows after attraction country merge: 52930

In [19]:
region_attraction = region.rename(columns={
    "regionid": "attraction_regionid",
    "region": "attraction_region",
    "continentid": "attraction_continentid"
})

master = master.merge(
    region_attraction,
    on="attraction_regionid",
    how="left",
    validate="many_to_one"
)

print("Rows after attraction region merge:", len(master))

Rows after attraction region merge: 52930

In [20]:
region_attraction = region.rename(columns={
    "regionid": "attraction_regionid",
    "region": "attraction_region",
    "continentid": "attraction_continentid"
})

master = master.merge(
    region_attraction,
    on="attraction_regionid",
    how="left",
    validate="many_to_one"
)

print("Rows after attraction region merge:", len(master))

Rows after attraction region merge: 52930

In [21]:
print("Final shape:", master.shape)

print("\nColumns:")
print(master.columns.tolist())

print("\nFirst 5 rows:")
display(master.head())

Final shape: (52930, 31)

Columns:
['transactionid', 'userid', 'visityear', 'visitmonth', 'visitmode', 'attractionid', 'rating', 'user_continentid', 'user_regionid', 'user_countryid', 'user_cityid', 'user_cityname', 'user_city_countryid', 'user_country', 'user_country_regionid', 'user_region', 'user_region_continentid', 'user_continent', 'attractioncityid', 'attractiontypeid', 'attraction', 'attractionaddress', 'attractiontype', 'attraction_cityname', 'attraction_countryid', 'attraction_country', 'attraction_regionid', 'attraction_region_x', 'attraction_continentid_x', 'attraction_region_y', 'attraction_continentid_y']

First 5 rows:

,transactionid,userid,visityear,visitmonth,visitmode,attractionid,rating,user_continentid,user_regionid,user_countryid,...,attractionaddress,attractiontype,attraction_cityname,attraction_countryid,attraction_country,attraction_regionid,attraction_region_x,attraction_continentid_x,attraction_region_y,attraction_continentid_y
0,3,70456,2022,10,2,640,5,5,21,163,...,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
1,8,7567,2022,10,4,640,5,2,8,48,...,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
2,9,79069,2022,10,3,640,5,2,9,54,...,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
3,10,31019,2022,10,3,640,3,5,17,135,...,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
4,15,43611,2022,10,2,640,3,5,21,163,...,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1

In [22]:
missing = master.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print("Columns containing missing values:")
print(missing)

Columns containing missing values:
user_cityid            8
user_cityname          8
user_city_countryid    8
dtype: int64

In [23]:
print("Original transaction rows:", len(transaction))
print("Final master rows:", len(master))

if len(transaction) == len(master):
    print("✅ All transaction records preserved.")
else:
    print("❌ Row count changed. Investigate merges.")

Original transaction rows: 52930
Final master rows: 52930
✅ All transaction records preserved.

In [24]:
duplicate_transactions = master["transactionid"].duplicated().sum()

print("Duplicate TransactionIds:", duplicate_transactions)

Duplicate TransactionIds: 0

In [25]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [26]:
output_path = "../data/processed/tourism_master.csv"

master.to_csv(output_path, index=False)

print(f"✅ Master dataset saved to: {output_path}")

✅ Master dataset saved to: ../data/processed/tourism_master.csv

In [27]:
mode_mapping = dict(
    zip(mode["visitmodeid"], mode["visitmode"])
)

print(mode_mapping)

{0: '-', 1: 'Business', 2: 'Couples', 3: 'Family', 4: 'Friends', 5: 'Solo'}

In [28]:
master["visitmode_name"] = master["visitmode"].map(mode_mapping)

print(master[["visitmode", "visitmode_name"]].drop_duplicates().sort_values("visitmode"))

      visitmode visitmode_name
1655          1       Business
0             2        Couples
2             3         Family
1             4        Friends
19            5           Solo

In [29]:
master = master.merge(
    user,
    on="userid",
    how="left",
    validate="many_to_one"
)

In [30]:
print("=" * 60)
print("FINAL DATASET VALIDATION")
print("=" * 60)

print("Rows:", master.shape[0])
print("Columns:", master.shape[1])

print("\nDuplicate TransactionIds:")
print(master["transactionid"].duplicated().sum())

print("\nMissing values:")
print(master.isnull().sum()[master.isnull().sum() > 0])

print("\nVisit Mode distribution:")
print(master["visitmode_name"].value_counts())

print("\nRating distribution:")
print(master["rating"].value_counts().sort_index())

============================================================
FINAL DATASET VALIDATION
============================================================
Rows: 52930
Columns: 36

Duplicate TransactionIds:
0

Missing values:
user_cityid            8
user_cityname          8
user_city_countryid    8
cityid                 8
dtype: int64

Visit Mode distribution:
visitmode_name
Couples     21620
Family      15217
Friends     10945
Solo         4525
Business      623
Name: count, dtype: int64

Rating distribution:
rating
1     1263
2     2035
3     7730
4    17966
5    23936
Name: count, dtype: int64