In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

master = pd.read_csv("../data/processed/tourism_master.csv")

print("Dataset shape:", master.shape)
display(master.head())

Dataset shape: (52930, 31)

,transactionid,userid,visityear,visitmonth,visitmode,attractionid,rating,user_continentid,user_regionid,user_countryid,user_cityid,user_cityname,user_city_countryid,user_country,user_country_regionid,user_region,user_region_continentid,user_continent,attractioncityid,attractiontypeid,attraction,attractionaddress,attractiontype,attraction_cityname,attraction_countryid,attraction_country,attraction_regionid,attraction_region_x,attraction_continentid_x,attraction_region_y,attraction_continentid_y
0,3,70456,2022,10,2,640,5,5,21,163,4341.0,Guildford,109.0,United Kingdom,21,Western Europe,5,Europe,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
1,8,7567,2022,10,4,640,5,2,8,48,464.0,Ontario,48.0,Canada,8,Northern America,2,America,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
2,9,79069,2022,10,3,640,5,2,9,54,774.0,Brazil,51.0,Brazil,9,South America,2,America,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
3,10,31019,2022,10,3,640,3,5,17,135,583.0,Zurich,48.0,Switzerland,17,Central Europe,5,Europe,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
4,15,43611,2022,10,2,640,3,5,21,163,1396.0,Manchester,51.0,United Kingdom,21,Western Europe,5,Europe,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1

In [2]:
print(master.dtypes)

transactionid                 int64
userid                        int64
visityear                     int64
visitmonth                    int64
visitmode                     int64
attractionid                  int64
rating                        int64
user_continentid              int64
user_regionid                 int64
user_countryid                int64
user_cityid                 float64
user_cityname                object
user_city_countryid         float64
user_country                 object
user_country_regionid         int64
user_region                  object
user_region_continentid       int64
user_continent               object
attractioncityid              int64
attractiontypeid              int64
attraction                   object
attractionaddress            object
attractiontype               object
attraction_cityname          object
attraction_countryid          int64
attraction_country           object
attraction_regionid           int64
attraction_region_x          object
attraction_continentid_x      int64
attraction_region_y          object
attraction_continentid_y      int64
dtype: object

In [3]:
missing = master.isnull().sum()

missing_df = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": (missing / len(master) * 100).round(2)
})

missing_df = missing_df[missing_df["Missing_Count"] > 0]
missing_df = missing_df.sort_values("Missing_Count", ascending=False)

display(missing_df)

                     Missing_Count  Missing_Percentage
user_cityid                      8                0.02
user_cityname                    8                0.02
user_city_countryid              8                0.02

In [4]:
for col in master.columns:
    if master[col].isnull().sum() > 0:
        print("\n" + "=" * 60)
        print("COLUMN:", col)
        print("=" * 60)
        display(master[master[col].isnull()].head(20))

============================================================
COLUMN: user_cityid
============================================================

,transactionid,userid,visityear,visitmonth,visitmode,attractionid,rating,user_continentid,user_regionid,user_countryid,user_cityid,user_cityname,user_city_countryid,user_country,user_country_regionid,user_region,user_region_continentid,user_continent,attractioncityid,attractiontypeid,attraction,attractionaddress,attractiontype,attraction_cityname,attraction_countryid,attraction_country,attraction_regionid,attraction_region_x,attraction_continentid_x,attraction_region_y,attraction_continentid_y
7134,10437,7175,2016,10,5,640,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
21190,33604,56972,2016,12,2,673,4,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,13,Seminyak Beach,Seminyak,Beaches,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
22283,35006,17595,2014,12,3,673,4,1,4,22,NaN,NaN,NaN,South Africa,4,Southern Africa,1,Africa,1,13,Seminyak Beach,Seminyak,Beaches,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
26249,42487,56972,2016,12,2,650,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,13,Sanur Beach,Sanur,Beaches,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
31689,67298,67461,2019,5,4,748,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
34600,71286,56972,2016,12,2,748,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
34799,71574,7175,2016,10,5,748,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
36610,74011,17595,2014,12,3,748,5,1,4,22,NaN,NaN,NaN,South Africa,4,Southern Africa,1,Africa,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1

============================================================
COLUMN: user_cityname
============================================================

,transactionid,userid,visityear,visitmonth,visitmode,attractionid,rating,user_continentid,user_regionid,user_countryid,user_cityid,user_cityname,user_city_countryid,user_country,user_country_regionid,user_region,user_region_continentid,user_continent,attractioncityid,attractiontypeid,attraction,attractionaddress,attractiontype,attraction_cityname,attraction_countryid,attraction_country,attraction_regionid,attraction_region_x,attraction_continentid_x,attraction_region_y,attraction_continentid_y
7134,10437,7175,2016,10,5,640,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
21190,33604,56972,2016,12,2,673,4,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,13,Seminyak Beach,Seminyak,Beaches,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
22283,35006,17595,2014,12,3,673,4,1,4,22,NaN,NaN,NaN,South Africa,4,Southern Africa,1,Africa,1,13,Seminyak Beach,Seminyak,Beaches,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
26249,42487,56972,2016,12,2,650,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,13,Sanur Beach,Sanur,Beaches,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
31689,67298,67461,2019,5,4,748,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
34600,71286,56972,2016,12,2,748,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
34799,71574,7175,2016,10,5,748,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
36610,74011,17595,2014,12,3,748,5,1,4,22,NaN,NaN,NaN,South Africa,4,Southern Africa,1,Africa,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1

============================================================
COLUMN: user_city_countryid
============================================================

,transactionid,userid,visityear,visitmonth,visitmode,attractionid,rating,user_continentid,user_regionid,user_countryid,user_cityid,user_cityname,user_city_countryid,user_country,user_country_regionid,user_region,user_region_continentid,user_continent,attractioncityid,attractiontypeid,attraction,attractionaddress,attractiontype,attraction_cityname,attraction_countryid,attraction_country,attraction_regionid,attraction_region_x,attraction_continentid_x,attraction_region_y,attraction_continentid_y
7134,10437,7175,2016,10,5,640,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
21190,33604,56972,2016,12,2,673,4,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,13,Seminyak Beach,Seminyak,Beaches,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
22283,35006,17595,2014,12,3,673,4,1,4,22,NaN,NaN,NaN,South Africa,4,Southern Africa,1,Africa,1,13,Seminyak Beach,Seminyak,Beaches,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
26249,42487,56972,2016,12,2,650,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,13,Sanur Beach,Sanur,Beaches,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
31689,67298,67461,2019,5,4,748,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
34600,71286,56972,2016,12,2,748,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
34799,71574,7175,2016,10,5,748,5,5,17,135,NaN,NaN,NaN,Switzerland,17,Central Europe,5,Europe,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1
36610,74011,17595,2014,12,3,748,5,1,4,22,NaN,NaN,NaN,South Africa,4,Southern Africa,1,Africa,1,72,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,1,Cameroon,1,Central Africa,1,Central Africa,1

In [5]:
if "user_cityname" in master.columns:
    master["user_cityname"] = master["user_cityname"].fillna("Unknown City")

if "attraction_cityname" in master.columns:
    master["attraction_cityname"] = master["attraction_cityname"].fillna("Unknown City")

In [6]:
user_geo_cols = [
    "user_cityid",
    "user_countryid",
    "user_regionid",
    "user_continentid"
]

available_cols = [c for c in user_geo_cols if c in master.columns]

display(
    master[master[available_cols].isnull().any(axis=1)][
        ["userid"] + available_cols
    ].drop_duplicates()
)

       userid  user_cityid  user_countryid  user_regionid  user_continentid
7134     7175          NaN             135             17                 5
21190   56972          NaN             135             17                 5
22283   17595          NaN              22              4                 1
31689   67461          NaN             135             17                 5

In [7]:
geo_name_cols = [
    "user_cityname",
    "user_country",
    "user_region",
    "user_continent"
]

for col in geo_name_cols:
    if col in master.columns:
        master[col] = master[col].fillna("Unknown")

In [8]:
print("Complete duplicate rows:", master.duplicated().sum())

Complete duplicate rows: 0

In [9]:
print("Duplicate TransactionIds:",
      master["transactionid"].duplicated().sum())

Duplicate TransactionIds: 0

In [10]:
print("Rating values:")
print(sorted(master["rating"].dropna().unique()))

Rating values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [11]:
invalid_ratings = master[
    ~master["rating"].isin([1, 2, 3, 4, 5])
]

print("Invalid ratings:", len(invalid_ratings))

if len(invalid_ratings) > 0:
    display(invalid_ratings.head())

Invalid ratings: 0

In [12]:
print("Rating values:")
print(sorted(master["rating"].dropna().unique()))

Rating values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [13]:
invalid_ratings = master[
    ~master["rating"].isin([1, 2, 3, 4, 5])
]

print("Invalid ratings:", len(invalid_ratings))

if len(invalid_ratings) > 0:
    display(invalid_ratings.head())

Invalid ratings: 0

In [14]:
print("Visit years:")
print(sorted(master["visityear"].dropna().unique()))

print("\nNumber of unique years:",
      master["visityear"].nunique())

Visit years:
[np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022)]

Number of unique years: 10

In [15]:
print(
    master[
        (master["visityear"] < 1900) |
        (master["visityear"] > 2100)
    ][["transactionid", "visityear"]].head()
)

Empty DataFrame
Columns: [transactionid, visityear]
Index: []

In [16]:
print("Visit months:")
print(sorted(master["visitmonth"].dropna().unique()))

Visit months:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]

In [17]:
invalid_months = master[
    ~master["visitmonth"].isin(range(1, 13))
]

print("Invalid months:", len(invalid_months))

Invalid months: 0

In [19]:
print("VisitMode IDs:")
print(sorted(master["visitmode"].dropna().unique()))

print("\nVisitMode names:")
visitmode_names = {
    1: "Business",
    2: "Couples",
    3: "Family",
    4: "Friends",
    5: "Solo"
}

print(
    master["visitmode"]
    .map(visitmode_names)
    .value_counts()
)

VisitMode IDs:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

VisitMode names:
visitmode
Couples     21620
Family      15217
Friends     10945
Solo         4525
Business      623
Name: count, dtype: int64

In [20]:
print("Unique attractions:",
      master["attractionid"].nunique())

print("\nMissing attraction IDs:",
      master["attractionid"].isnull().sum())

print("\nMissing attraction names:",
      master["attraction"].isnull().sum())

Unique attractions: 30

Missing attraction IDs: 0

Missing attraction names: 0

In [21]:
text_columns = master.select_dtypes(include="object").columns

for col in text_columns:
    master[col] = master[col].str.strip()

In [22]:
display(master[text_columns].head())

,user_cityname,user_country,user_region,user_continent,attraction,attractionaddress,attractiontype,attraction_cityname,attraction_country,attraction_region_x,attraction_region_y
0,Guildford,United Kingdom,Western Europe,Europe,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,Cameroon,Central Africa,Central Africa
1,Ontario,Canada,Northern America,America,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,Cameroon,Central Africa,Central Africa
2,Brazil,Brazil,South America,America,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,Cameroon,Central Africa,Central Africa
3,Zurich,Switzerland,Central Europe,Europe,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,Cameroon,Central Africa,Central Africa
4,Manchester,United Kingdom,Western Europe,Europe,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,Cameroon,Central Africa,Central Africa

In [23]:
categorical_columns = [
    "visitmode_name",
    "attraction",
    "attractiontype",
    "user_cityname",
    "user_country",
    "user_region",
    "user_continent",
    "attraction_cityname",
    "attraction_country",
    "attraction_region",
    "attraction_continent"
]

categorical_columns = [
    c for c in categorical_columns
    if c in master.columns
]

for col in categorical_columns:
    master[col] = master[col].astype("category")

In [25]:
print("=" * 60)
print("FINAL CLEANING VALIDATION")
print("=" * 60)

print("Shape:", master.shape)

print("\nDuplicate rows:",
      master.duplicated().sum())

print("\nDuplicate TransactionIds:",
      master["transactionid"].duplicated().sum())

print("\nMissing values:")
print(
    master.isnull().sum()[
        master.isnull().sum() > 0
    ]
)

print("\nRating values:")
print(sorted(master["rating"].dropna().unique()))

print("\nVisit modes:")
print(
    master["visitmode"]
    .map(visitmode_names)
    .value_counts()
)

print("\nAttractions:",
      master["attractionid"].nunique())

============================================================
FINAL CLEANING VALIDATION
============================================================
Shape: (52930, 31)

Duplicate rows: 0

Duplicate TransactionIds: 0

Missing values:
user_cityid            8
user_city_countryid    8
dtype: int64

Rating values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Visit modes:
visitmode
Couples     21620
Family      15217
Friends     10945
Solo         4525
Business      623
Name: count, dtype: int64

Attractions: 30

In [26]:
output_path = "../data/processed/tourism_master_cleaned.csv"

master.to_csv(
    output_path,
    index=False
)

print(f"✅ Cleaned dataset saved to: {output_path}")

✅ Cleaned dataset saved to: ../data/processed/tourism_master_cleaned.csv